<?php

namespace JsPhpize\Lexer\Patterns;

use Generator;
use JsPhpize\Lexer\Lexer;
use JsPhpize\Lexer\Pattern;

class StringPattern extends Pattern
{
    public function __construct($priority)
    {
        parent::__construct($priority, 'string', '"(?:\\\\.|[^"\\\\])*"|\'(?:\\\\.|[^\'\\\\])*\'|`(?:\\\\.|[^`\\\\])*`');
    }

    public function lexWith(Lexer $lexer): Generator
    {
        $rest = $lexer->rest();

        parent::lexWith($lexer); // TODO: Change the autogenerated stub
    }
}
